package com.anhdt.doranewsvermain.model.videotest;

import java.util.ArrayList;

public class CreateVideoData {
    public static ArrayList<Video> createVideos() {
        ArrayList<Video> arrayList = new ArrayList<>();
        arrayList.add(new Video("ZV6SR3azDGE",
                "https://www.youtube.com/watch?v=ZV6SR3azDGE",
                "Những thí sinh đặc biệt nhất của kỳ thi THPT quốc gia 2019 I Góc bàn luận I",
                "47",
                "26/6/2019",
                "https://i.ytimg.com/vi/ZV6SR3azDGE/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "6:39",
                3, 0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "[TIN TỔNG HỢP 24H] Lãnh đạo VFF xin nghỉ vì ông Park Hang-seo I Chào buổi sáng",
                "60",
                "25/6/2019",
                "https://i.ytimg.com/vi/dgR5EIrP80E/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "8:20", 6,
                0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "4 nguyên nhân khiến SKT đang trượt dài tại LCK mùa hè 2019 I Góc bàn luận",
                "40",
                "24/6/2019",
                "https://img.youtube.com/vi/u9GiYXxdCTo/0.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "4:20", 8,
                0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "[TIN TỔNG HỢP 24H] Lãnh đạo VFF xin nghỉ vì ông Park Hang-seo I Chào buổi sáng",
                "60",
                "25/6/2019",
                "https://i.ytimg.com/vi/dgR5EIrP80E/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "8:20", 6,
                0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "[TIN TỔNG HỢP 24H] Lãnh đạo VFF xin nghỉ vì ông Park Hang-seo I Chào buổi sáng",
                "60",
                "25/6/2019",
                "https://i.ytimg.com/vi/dgR5EIrP80E/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "8:20", 6,
                0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "[TIN TỔNG HỢP 24H] Lãnh đạo VFF xin nghỉ vì ông Park Hang-seo I Chào buổi sáng",
                "60",
                "25/6/2019",
                "https://i.ytimg.com/vi/dgR5EIrP80E/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "8:20", 6,
                0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "[TIN TỔNG HỢP 24H] Lãnh đạo VFF xin nghỉ vì ông Park Hang-seo I Chào buổi sáng",
                "60",
                "25/6/2019",
                "https://i.ytimg.com/vi/dgR5EIrP80E/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "8:20", 6,
                0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "[TIN TỔNG HỢP 24H] Lãnh đạo VFF xin nghỉ vì ông Park Hang-seo I Chào buổi sáng",
                "60",
                "25/6/2019",
                "https://i.ytimg.com/vi/dgR5EIrP80E/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "8:20", 6,
                0));
        arrayList.add(new Video("dgR5EIrP80E",
                "https://www.youtube.com/watch?v=dgR5EIrP80E",
                "[TIN TỔNG HỢP 24H] Lãnh đạo VFF xin nghỉ vì ông Park Hang-seo I Chào buổi sáng",
                "60",
                "25/6/2019",
                "https://i.ytimg.com/vi/dgR5EIrP80E/hqdefault.jpg",
                "Phóng Tin",
                "https://yt3.ggpht.com/a/AGF-l7_JUdtbOoGHCqlc9VzKurJ62219NXnGV4LRLA=s288-mo-c-c0xffffffff-rj-k-no",
                "8:20", 6,
                0));
        return arrayList;
    }
}
